name: CI/CD Pipeline

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build_and_test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: Install dependencies
     run: |
       sudo apt-get update
       sudo apt-get install -y build-essential libcriterion-dev

   - name: Create build directories
     run: make dirs

   - name: Build debug version
     run: make debug

   - name: Run tests
     run: make test

   - name: Build release version 
     run: make release

   - name: Build examples
     run: make examples

   - name: Clean
     run: make clean

 static_analysis:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: Install cppcheck
     run: sudo apt-get install -y cppcheck

   - name: Run cppcheck
     run: cppcheck --enable=all --suppress=missingInclude .

 code_coverage:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: Install dependencies
     run: |
       sudo apt-get update
       sudo apt-get install -y lcov libcriterion-dev

   - name: Build with coverage
     run: |
       make clean
       make CFLAGS="-fprofile-arcs -ftest-coverage" test

   - name: Generate coverage report
     run: |
       lcov --capture --directory . --output-file coverage.info
       lcov --remove coverage.info '/usr/*' --output-file coverage.info

   - name: Upload coverage report
     uses: actions/upload-artifact@v3
     with:
       name: code-coverage-report
       path: coverage.info
